apiVersion: apps/v1beta2 # for versions after 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: k8s/ui:v1
        ports:
        - containerPort: 3000
