apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: api-default
  labels:
    app: api
spec:
  destination:
    name: api
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
  - labels:
      version: v2
    weight: 0
