apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: training-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: training:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        ports:
        - containerPort: 3000
        env:
        - name: SHOULD_FAIL_WITHIN
          value: "5000"
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              name: training-secrets
              key: redis
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        emptyDir: {}
