apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        imagePullPolicy: Always
        image: gcr.io/training-193616/ui:v1
        ports:
        - containerPort: 80
