apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-v1
  labels:
    app: api
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        version: v1
    spec:
      containers:
      - name: api
        image: k8s/api:v1
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "v1"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-v2
  labels:
    app: api
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        version: v2
    spec:
      containers:
      - name: api
        image: k8s/api:v1
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "v2"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
