apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: github-circuit-breaker
spec:
  destination:
    name: github
  circuitBreaker:
    simpleCb:
      httpMaxPendingRequests: 1
      sleepWindow: 3m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
